const FAKE_POPULARS = [
  {
    backdrop_path: "/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg",
    first_air_date: "2023-05-08",
    genre_ids: [18, 80, 10766],
    id: 209265,
    name: "Terra e Paixão",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Terra e Paixão",
    overview: "",
    popularity: 3306.351,
    poster_path: "/voaKRrYExZNkf1E4FZExU7fTd8w.jpg",
    vote_average: 7.77,
    vote_count: 46,
  },
];

const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 342.584,
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 12063,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lcSvkJ2Rob3ICIOCUJahw3kgSYZ.jpg",
    id: 216390,
    name: "Woman in a Veil",
    original_language: "ko",
    original_name: "비밀의 여자",
    overview:
      "Jung Gyul Wool loses her vision and ability to walk because of her materialistic husband and his mistress. Despite her shortcomings, she hatches a plot to seek revenge.",
    poster_path: "/5ERr09UrnVm0hdXBeefNVtQMxI.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 1343.849,
    first_air_date: "2023-03-14",
    vote_average: 6.51,
    vote_count: 50,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 318.145,
    first_air_date: "2016-07-15",
    vote_average: 8.628,
    vote_count: 15869,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/jsXKG9uppnPrhqFNhImllyCfLhl.jpg",
    id: 65930,
    name: "My Hero Academia",
    original_language: "ja",
    original_name: "僕のヒーローアカデミア",
    overview:
      "In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that won't stop him from enrolling in a prestigious hero academy. Now, he'll get his first taste of brutal rivalry from other schools as he braves the cutthroat, no-holds-barred provisional license exam.",
    poster_path: "/ivOLM47yJt90P19RH1NvJrAJz9F.jpg",
    media_type: "tv",
    genre_ids: [10759, 16],
    popularity: 40.805,
    first_air_date: "2016-04-03",
    vote_average: 8.684,
    vote_count: 4408,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/57clBMPX25NNO6nmDw3TV3zQaQE.jpg",
    id: 114472,
    name: "Secret Invasion",
    original_language: "en",
    original_name: "Secret Invasion",
    overview:
      "Nick Fury and Talos discover a faction of shapeshifting Skrulls who have been infiltrating Earth for years.",
    poster_path: "/f5ZMzzCvt2IzVDxr54gHPv9jlC9.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 10759],
    popularity: 1465.573,
    first_air_date: "2023-06-21",
    vote_average: 7.366,
    vote_count: 522,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
    id: 94722,
    name: "Tagesschau",
    original_language: "de",
    original_name: "Tagesschau",
    overview:
      "German daily news program, the oldest still existing program on German television.",
    poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
    media_type: "tv",
    genre_ids: [10763],
    popularity: 3230.014,
    first_air_date: "1952-12-26",
    vote_average: 7.596,
    vote_count: 68,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: "/xE8pn907KEqnyXCtDdxbaebs2qT.jpg",
    id: 119893,
    name: "Girl2K",
    original_language: "th",
    original_name: "สาวออฟฟิศ 2000 ปี",
    overview: "",
    poster_path: "/u29dpPKfkp2A15TModkXWn9oLuQ.jpg",
    media_type: "tv",
    genre_ids: [35, 10765],
    popularity: 1.271,
    first_air_date: "2021-02-17",
    vote_average: 1,
    vote_count: 1,
    origin_country: ["TH"],
  },
  {
    adult: false,
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 228.356,
    first_air_date: "2022-11-23",
    vote_average: 8.57,
    vote_count: 7334,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    id: 60574,
    name: "Peaky Blinders",
    original_language: "en",
    original_name: "Peaky Blinders",
    overview:
      "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.",
    poster_path: "/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 600.006,
    first_air_date: "2013-09-12",
    vote_average: 8.544,
    vote_count: 8639,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/foGkPxpw9h8zln81j63mix5B7m8.jpg",
    id: 71912,
    name: "The Witcher",
    original_language: "en",
    original_name: "The Witcher",
    overview:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    poster_path: "/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
    media_type: "tv",
    genre_ids: [18, 10759, 10765],
    popularity: 1085.763,
    first_air_date: "2019-12-20",
    vote_average: 8.153,
    vote_count: 4963,
    origin_country: ["US"],
  },
];

export { FAKE_POPULARS, FAKE_RECOMMENDATIONS };
